process.env.PUBLIC_STELLAR_NETWORK = "TESTNET";
process.env.PUBLIC_STELLAR_NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
process.env.PUBLIC_STELLAR_RPC_URL = "https://soroban-testnet.stellar.org";
process.env.PUBLIC_STELLAR_HORIZON_URL = "https://horizon-testnet.stellar.org";
process.env.PUBLIC_PROMPT_HASH_CONTRACT_ID = "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
process.env.PUBLIC_STELLAR_NATIVE_ASSET_CONTRACT_ID = "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
